table aging
	lineageTag: 2c122960-0211-453f-ab92-7c3c846466d6

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: fb33c1ab-07a1-4169-9960-2731866ba0b5
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Aging
		dataType: int64
		formatString: 0
		lineageTag: 21af639b-0f7a-4eaa-b1e5-22c46d867322
		summarizeBy: sum
		sourceColumn: Aging

		annotation SummarizationSetBy = Automatic

	partition aging = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("Zc/LCcAwDAPQXXwOTfxr0llC9l+jYBcs6PUhC3lv4s5dhhg18kGnbZIS8xAFyYz9xEt0hdwg2TNBNGSB2DXDHkxd2cUDkJNgueYlw3T/KMUrJCVm+J7XwwZXQue8", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Date = _t, Aging = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Date", type date}, {"Aging", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

