table support_staff
	lineageTag: a70a42f4-1661-4be5-9fda-80a26196f579

	column 'Support Staff'
		dataType: int64
		formatString: 0
		lineageTag: 14ad84fd-30ac-43b0-bc10-4c181881c35f
		summarizeBy: sum
		sourceColumn: Support Staff

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7ff3e8bf-d3ed-46e9-bdc3-4950b924bd11
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 161f5d70-bc71-44ba-9f87-ad3a25789f2d
			defaultHierarchy: LocalDateTable_28c30816-2813-41f1-8a66-9e19c0d31349.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition support_staff = m
		mode: import
		queryGroup: Attrition
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("Zc5BCsAgEAPAv+x5wc1qW32L+P9vGC+loafAkEDmNCDMDQUlI5stJ0UnpVKSqlIltT9dXxqDcksJID1KZ9eFmG5D6XxAvLY2", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Support Staff" = _t, Date = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Support Staff", Int64.Type}, {"Date", type date}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

